package com.muyu.entity;

import java.io.Serializable;

public class DoubleColorBall implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.id
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_one
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_tow
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallTow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_three
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_four
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_five
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallFive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.red_ball_six
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer redBallSix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.blue_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer blueBall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.bonus
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Long bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.purchase_amount
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private Integer purchaseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column double_color_ball.date_award
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private String dateAward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table double_color_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table double_color_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public DoubleColorBall(Long id, Integer redBallOne, Integer redBallTow, Integer redBallThree, Integer redBallFour, Integer redBallFive, Integer redBallSix, Integer blueBall, Long bonus, Integer purchaseAmount, String dateAward) {
        this.id = id;
        this.redBallOne = redBallOne;
        this.redBallTow = redBallTow;
        this.redBallThree = redBallThree;
        this.redBallFour = redBallFour;
        this.redBallFive = redBallFive;
        this.redBallSix = redBallSix;
        this.blueBall = blueBall;
        this.bonus = bonus;
        this.purchaseAmount = purchaseAmount;
        this.dateAward = dateAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table double_color_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public DoubleColorBall() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.id
     *
     * @return the value of double_color_ball.id
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.id
     *
     * @param id the value for double_color_ball.id
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_one
     *
     * @return the value of double_color_ball.red_ball_one
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallOne() {
        return redBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_one
     *
     * @param redBallOne the value for double_color_ball.red_ball_one
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallOne(Integer redBallOne) {
        this.redBallOne = redBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_tow
     *
     * @return the value of double_color_ball.red_ball_tow
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallTow() {
        return redBallTow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_tow
     *
     * @param redBallTow the value for double_color_ball.red_ball_tow
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallTow(Integer redBallTow) {
        this.redBallTow = redBallTow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_three
     *
     * @return the value of double_color_ball.red_ball_three
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallThree() {
        return redBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_three
     *
     * @param redBallThree the value for double_color_ball.red_ball_three
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallThree(Integer redBallThree) {
        this.redBallThree = redBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_four
     *
     * @return the value of double_color_ball.red_ball_four
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallFour() {
        return redBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_four
     *
     * @param redBallFour the value for double_color_ball.red_ball_four
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallFour(Integer redBallFour) {
        this.redBallFour = redBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_five
     *
     * @return the value of double_color_ball.red_ball_five
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallFive() {
        return redBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_five
     *
     * @param redBallFive the value for double_color_ball.red_ball_five
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallFive(Integer redBallFive) {
        this.redBallFive = redBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.red_ball_six
     *
     * @return the value of double_color_ball.red_ball_six
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getRedBallSix() {
        return redBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.red_ball_six
     *
     * @param redBallSix the value for double_color_ball.red_ball_six
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setRedBallSix(Integer redBallSix) {
        this.redBallSix = redBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.blue_ball
     *
     * @return the value of double_color_ball.blue_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getBlueBall() {
        return blueBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.blue_ball
     *
     * @param blueBall the value for double_color_ball.blue_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setBlueBall(Integer blueBall) {
        this.blueBall = blueBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.bonus
     *
     * @return the value of double_color_ball.bonus
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Long getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.bonus
     *
     * @param bonus the value for double_color_ball.bonus
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setBonus(Long bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.purchase_amount
     *
     * @return the value of double_color_ball.purchase_amount
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public Integer getPurchaseAmount() {
        return purchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.purchase_amount
     *
     * @param purchaseAmount the value for double_color_ball.purchase_amount
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setPurchaseAmount(Integer purchaseAmount) {
        this.purchaseAmount = purchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column double_color_ball.date_award
     *
     * @return the value of double_color_ball.date_award
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public String getDateAward() {
        return dateAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column double_color_ball.date_award
     *
     * @param dateAward the value for double_color_ball.date_award
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    public void setDateAward(String dateAward) {
        this.dateAward = dateAward == null ? null : dateAward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table double_color_ball
     *
     * @mbg.generated Sat Jul 25 13:07:35 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", redBallOne=").append(redBallOne);
        sb.append(", redBallTow=").append(redBallTow);
        sb.append(", redBallThree=").append(redBallThree);
        sb.append(", redBallFour=").append(redBallFour);
        sb.append(", redBallFive=").append(redBallFive);
        sb.append(", redBallSix=").append(redBallSix);
        sb.append(", blueBall=").append(blueBall);
        sb.append(", bonus=").append(bonus);
        sb.append(", purchaseAmount=").append(purchaseAmount);
        sb.append(", dateAward=").append(dateAward);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}