package com.muyu.entity;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_num
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Long orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private String orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paid_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private String paidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product_id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buy_counts
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Integer buyCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paid_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private Date paidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Orders(Long id, Long orderNum, String orderStatus, String orderAmount, String paidAmount, Long productId, Integer buyCounts, Date createTime, Date paidTime) {
        this.id = id;
        this.orderNum = orderNum;
        this.orderStatus = orderStatus;
        this.orderAmount = orderAmount;
        this.paidAmount = paidAmount;
        this.productId = productId;
        this.buyCounts = buyCounts;
        this.createTime = createTime;
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Orders() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_num
     *
     * @return the value of orders.order_num
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Long getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_num
     *
     * @param orderNum the value for orders.order_num
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setOrderNum(Long orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_amount
     *
     * @return the value of orders.order_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public String getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_amount
     *
     * @param orderAmount the value for orders.order_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount == null ? null : orderAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paid_amount
     *
     * @return the value of orders.paid_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public String getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paid_amount
     *
     * @param paidAmount the value for orders.paid_amount
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount == null ? null : paidAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product_id
     *
     * @return the value of orders.product_id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product_id
     *
     * @param productId the value for orders.product_id
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buy_counts
     *
     * @return the value of orders.buy_counts
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Integer getBuyCounts() {
        return buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buy_counts
     *
     * @param buyCounts the value for orders.buy_counts
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setBuyCounts(Integer buyCounts) {
        this.buyCounts = buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paid_time
     *
     * @return the value of orders.paid_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paid_time
     *
     * @param paidTime the value for orders.paid_time
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Jul 25 13:08:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", paidAmount=").append(paidAmount);
        sb.append(", productId=").append(productId);
        sb.append(", buyCounts=").append(buyCounts);
        sb.append(", createTime=").append(createTime);
        sb.append(", paidTime=").append(paidTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}